name: hogge
dependencies:
- colorama=0.3.3=py34_0
- jinja2=2.8=py34_0
- markupsafe=0.23=py34_0
- msvc_runtime=1.0.0=vc10_0
- pip=7.1.2=py34_0
- py=1.4.30=py34_0
- py2exe=0.9.2.0=py34_0
- pytest=2.8.1=py34_0
- python=3.4.3=3
- pyyaml=3.11=py34_2
- setuptools=18.4=py34_0
- wheel=0.26.0=py34_1
- xlsxwriter=0.7.6=py34_0
- pip:
  - alembic==0.6.5
  - dataset==0.5.5
  - mako==1.0.0
  - pyirsdk==1.1.4
  - python-slugify==0.0.7
  - unidecode==0.4.16

